name: OpenShift

env:
  REGISTRY: docker.io/cloudattech
  REGISTRY_USER: cloudattech
  REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "amol-tapase-dev"
  APP_NAME: "django-app"
  TAG: "latest"

on: [ workflow_dispatch]

jobs:
  openshift-ci-cd:
    name: Build
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Sourcecode
          uses: actions/checkout@v3

        - name: Build from Dockerfile
          id: image-build
          uses: redhat-actions/buildah-build@v2
          with:
           image: ${{ env.APP_NAME }}
           tags: ${{ env.TAG }}
           dockerfiles: |
            ./Dockerfile

        - name: Push to registry
          id: push-to-registry
          uses: redhat-actions/push-to-registry@v2
          with:
           image: ${{ steps.image-build.outputs.image }}
           tags: ${{ steps.image-build.outputs.tags }}
           registry: ${{ env.REGISTRY }}
           username: ${{ env.REGISTRY_USER }}
           password: ${{ env.REGISTRY_PASSWORD }}
